//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AragonClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AragonPharmarcyEntities : DbContext
    {
        public AragonPharmarcyEntities()
            : base("name=AragonPharmarcyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClinic> tblClinics { get; set; }
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblEmployeeTraining> tblEmployeeTrainings { get; set; }
        public virtual DbSet<tblJobtitle> tblJobtitles { get; set; }
        public virtual DbSet<tblDrug> tblDrugs { get; set; }
        public virtual DbSet<tblRefill> tblRefills { get; set; }
        public virtual DbSet<tblRx> tblRxes { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblHealthPlan> tblHealthPlans { get; set; }
        public virtual DbSet<tblHousehold> tblHouseholds { get; set; }
    }
}
