//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AragonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblRxes = new HashSet<tblRx>();
        }
    
        public int CustID { get; set; }
        public string CustFirst { get; set; }
        public string CustLast { get; set; }
        public string Phone { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public decimal Balance { get; set; }
        public bool ChildproofCap { get; set; }
        public string PlanID { get; set; }
        public short HouseID { get; set; }
        public Nullable<bool> HeadHH { get; set; }
        public string Allergies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRx> tblRxes { get; set; }
        public virtual tblHealthPlan tblHealthPlan { get; set; }
        public virtual tblHousehold tblHousehold { get; set; }
    }
}
