//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AragonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDrug()
        {
            this.tblRxes = new HashSet<tblRx>();
        }
    
        public string DIN { get; set; }
        public string Name { get; set; }
        public bool Generic { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public decimal Dosage { get; set; }
        public string DosageForm { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public decimal fee { get; set; }
        public string Interactions { get; set; }
        public string Supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRx> tblRxes { get; set; }
    }
}
