//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AragonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblEmployeeTrainings = new HashSet<tblEmployeeTraining>();
            this.tblRefills = new HashSet<tblRefill>();
        }
    
        public short EmpID { get; set; }
        public string EmpFirst { get; set; }
        public string EmpMI { get; set; }
        public string EmpLast { get; set; }
        public string SINs { get; set; }
        public string DOB { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public byte JobID { get; set; }
        public string Memo { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public string ReviewDate { get; set; }
    
        public virtual tblJobtitle tblJobtitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeTraining> tblEmployeeTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRefill> tblRefills { get; set; }
    }
}
