//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AragonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRx()
        {
            this.tblRefills = new HashSet<tblRefill>();
        }
    
        public short PrescriptionID { get; set; }
        public string DIN { get; set; }
        public byte Quantity { get; set; }
        public string Unit { get; set; }
        public string Date { get; set; }
        public string ExpireDate { get; set; }
        public Nullable<byte> Refills { get; set; }
        public Nullable<bool> AutoRefill { get; set; }
        public Nullable<byte> RefillsUsed { get; set; }
        public string Instructions { get; set; }
        public int CustID { get; set; }
        public short DoctorID { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblDrug tblDrug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRefill> tblRefills { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
